module.exports.generateApiKey = require('./services.generateApiKey')
module.exports.getAllApiKey = require('./services.getAllApiKey')
module.exports.revealkey = require('./services.revealkey')
module.exports.deleteAPIkey = require('./services.deleteAPIkey')
module.exports.deleteAPIkey = require('./services.deleteAPIkey')
module.exports.getApiKey = require('./services.getApiKey')